#название запускаемого файла
BIN		:=getpic_e.com

#поддиректория инсталляции в release
INSTDIR := bin

#тип вводавывода TTY или BDOS
CONSOLE := TTY

#файлы .с
SRCC	:= main.c
#файлы .h
SRCH	:=
#файлы .asm
SRCA	:=
#линковочный файл-скрипт. можно не указывать, тогда будет использоватся стандартный
XCLFILE	:= lnk.xcl


include ../iarlib/iar.mk
